#!/bin/bash
# Quick reference script for common commands

echo "========================================"
echo "FRA532 Lab 1 - Quick Reference"
echo "========================================"
echo ""
echo "1. Build the workspace:"
echo "   cd /home/ambushee/fibo_mobilerobot"
echo "   colcon build --symlink-install"
echo "   source install/setup.bash"
echo ""
echo "2. Check bag file info:"
echo "   ros2 bag info FRA532_LAB1_DATASET/fibo_floor3_seq00/"
echo ""
echo "3. Run Part 1 (EKF Odometry):"
echo "   Terminal 1: ros2 bag play FRA532_LAB1_DATASET/fibo_floor3_seq00/"
echo "   Terminal 2: ros2 launch fra532_lab1_part1 odometry.launch.py"
echo ""
echo "4. Run Part 2 (ICP Odometry):"
echo "   Terminal 1: ros2 bag play FRA532_LAB1_DATASET/fibo_floor3_seq00/"
echo "   Terminal 2: ros2 launch fra532_lab1_part2 icp_odometry.launch.py"
echo ""
echo "5. Run Part 3 (SLAM):"
echo "   Terminal 1: ros2 bag play FRA532_LAB1_DATASET/fibo_floor3_seq00/"
echo "   Terminal 2: ros2 launch fra532_lab1_part3 slam_toolbox.launch.py"
echo ""
echo "6. Record odometry data:"
echo "   ros2 bag record /wheel_odom /ekf_odom /icp_odom -o results"
echo ""
echo "7. View topics:"
echo "   ros2 topic list"
echo "   ros2 topic echo /ekf_odom"
echo ""
echo "8. Visualize in RViz:"
echo "   rviz2"
echo ""
echo "========================================"
